name = "LennardJones"
uuid = "25554a8e-05c9-411c-9e60-48f3ce0dd2d5"
authors = ["joeleaves <joel.eaves@colorado.edu> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
DataFrames = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
